var personName = "USman ShaiKh";
console.log("Name in uppercase : ".concat(personName.toUpperCase()));
console.log("Name in lowercase : ".concat(personName.toLowerCase()));
var step1 = personName.split(" ");
var step2 = step1.map(function (word) { return word.charAt(0).toUpperCase() + word.substr(1).toLowerCase(); });
var step3 = step2.join("");
console.log("Name in titlecase: ".concat(step3));
console.log(step1);
console.log(step2);
console.log(step3);
